name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: webpronl/reveal-md:latest
      options:
        --entrypoint=''
      volumes:
        - ${{github.workspace}}:/slides
        - /tmp/artifacts:/tmp/artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: /app/bin/reveal-md.js /slides/ --static /tmp/artifacts/presentation/

      - name: Install upload-pages-artifact dependency
        run: apk add tar

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: /tmp/artifacts/presentation/

  release-and-deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://rescribet.github.io/slides/

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        if: startsWith(github.ref, 'refs/tags/')
